services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "file:./db/aplikasi.db"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./db/aplikasi.db